services:

  broker:
    build: ./broker
    ports:
      - "8080:8080"
      - "8000:8000"

  sensor:
    build: ./sensor
    depends_on:
      - broker
    stdin_open: true
    tty: true

  atuador:
    build: ./atuador
    depends_on:
      - broker
    stdin_open: true
    tty: true

  cliente:
    build: ./cliente
    depends_on:
      - broker
    stdin_open: true
    tty: true